name: Create Release

on:
  push:
    branches: [ "main" ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get the current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"
      
      # Create Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: release-${{ steps.date.outputs.date }}
          release_name: Release ${{ steps.date.outputs.date }}
          draft: false
          prerelease: false

      - name: Upload Dockerfile to Release
        run: |
          curl -v \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @Dockerfile \
            "${{ steps.create_release.outputs.upload_url }}?name=Dockerfile&label=Dockerfile"
      
      - name: Upload Dockerfile.bullseye to Release
        run: |
          curl -v \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @Dockerfile.bullseye \
            "${{ steps.create_release.outputs.upload_url }}?name=Dockerfile.bullseye&label=Dockerfile.bullseye"
      
      - name: Upload entrypoint.sh to Release
        run: |
          curl -v \
            -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Content-Type: application/octet-stream" \
            --data-binary @entrypoint.sh \
            "${{ steps.create_release.outputs.upload_url }}?name=entrypoint.sh&label=entrypoint.sh"
